controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
#app_lucky_number:
#    path: /lucky
#    controller: App\Controller\LuckyController::number